spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_FROM}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: productlib
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

cors:
  originPatterns: http://localhost:8100,https://shop.meshhdawi.com,https://admin.meshhdawi.com,http://localhost:8101

logging:
  level:
    org.springframework.mail: DEBUG

meshhdawi:
  email-config:
    email: ${EMAIL_FROM}
  fileStorage:
    uploadDir: src/main/resources/static/uploads
  jwt-secret: ${JWT_SECRET:your-super-secure-256-bit-secret-key-12345}
