spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_FROM}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: productlib
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

cors:
  originPatterns: http://localhost:8100,https://shop.meshhdawi.com,https://admin.meshhdawi.com

logging:
  level:
    org.springframework.mail: DEBUG

meshhdawi:
  email-config:
    email: ${EMAIL_FROM}

