spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productlib
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: productlib
  jpa:
    show-sql: false

meshhdawi:
  telegram-token: ${TELEGRAM_TOKEN}