version: '3'
services:
  postgres-product-lib:
    container_name: product-lib-db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "productlib"
    ports:
      - "5433:5432" # Host port 5433 mapped to container port 5432
    volumes:
      - ~/postgres-productlib-data:/var/lib/postgresql/data
